server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: file:///C:/opt/workspaces/np-microservices-sample-02/np-ms-sample-02-config
          search-paths:
          - /config
          timeout: 60000 # default is 5000 ms
          