server:
  port: 9090

spring:

  # Active profile
  profiles.active: dev
  
  # JSON serialization settings
  jackson:
    default-property-inclusion: NON_NULL
    
    serialization:
      write-null-map-values: false 
      
    deserialization:
      accept-single-value-as-array: true

# Spring Lemon related properties
lemon:

  # First ADMIN user
  admin:
    username: admin@example.com
    password: admin!
    
   # Spring Lemon flags
   # enabled:
      # json-prefix: false
      
  # Properties to be passed to client
  shared:
    fooBar: 123...